= Google News Reader With Mongo DB
:docs: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference
:github: https://github.com/spring-projects/spring-boot

This is project which fetch Google News from API and insert it to MongoDB database added in MongoLab.

== Installation and Getting Started
The {docs}/html/[reference documentation] includes detailed
{docs}/html/getting-started.html#getting-started-installing-spring-boot[installation
instructions] as well as a comprehensive
{docs}/html/getting-started.html#getting-started-first-application[``getting started``]
guide.

Here is a quick teaser of a Main Class of this application in Java:
[source,java,indent=0]
----
package com.dext.rest;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
public class RestApplication {

	public static void main(String[] args) {
		SpringApplication.run(RestApplication.class, args);
	}

}
----

== Building Project
You don't need to build from source to use Spring Boot (binaries in
https://repo.spring.io[repo.spring.io]), but if you want to try out the latest and
greatest, Spring Boot can be easily built with the
https://github.com/apache/maven[maven]. You also need JDK 1.8.

[indent=0]
----
	$ ./mvn clean install
----

If you want to build with the regular `mvn` command, you will need
https://maven.apache.org/run-maven/index.html[Maven v3.5.0 or above].

== Run Application
Ways to run application:

* From Eclipse: By running main class RestApplication.java as 'Java Application'. 
* From STS: By running application as 'Spring Boot Application'.
* From cmd: Go to Project directory and run below command.

[indent=0]
----
  $ ./mvn spring-boot:run
----
